### PR TITLE
Pull request #1

### PR DESCRIPTION
**Pull request by Haarolean**

### CODE REVIEW

**Comment by TheJeterLP** [comment]
Thanks for that :)

**Comment by Haarolean** [comment]
@TheJeterLP No problems :)
Btw, i've reported many bugs at bug.admincmd.com. There are few high-priority, seems like Balor is currently inactive.

**Comment by TheJeterLP** [comment]
@Zeluboba yes he is, that's also why the Jenkins is currently down and I cant restart it :(

I'll look into these bugs now.

**Comment by Haarolean** [comment]
@TheJeterLP Yes, I noticed that jenkins is down. Couldn't take a look for newer builds. Thank you.

**Comment by TheJeterLP** [comment]
http://bug.admincmd.com/view.php?id=541 has been resolved with https://github.com/AdminCMD/AdminCMD/commit/db6961da7182eb2dd2af6b810fd7127ea730d8db

**Comment by TheJeterLP** [comment]
For first, new jenkins is at https://jeter.ci.cloudbees.com/job/AdminCMD/

**Comment by TheJeterLP** [comment]
@Zeluloba also please keep the resolved status in the Bugtracker so we see instantly that it has been fixed.

**Pull request merged**
